### ISSUE TITLE
Port GSI master to WCOSS2

### ISSUE THREAD

**Issue by XianwuXue-NOAA** [NOAA-EMC/GSI#203]
Due to the new changes of the environment on WCOSS2, so I updated the modules and their version.

**Comment by XianwuXue-NOAA** [comment]
@MichaelLueken-NOAA I compiled it on Cactus, this is my build log file: /lfs/h2/emc/ens/noscrub/Xianwu.Xue/gw/gw_feature_gefs_v12_github_port2acorn/sorc/gsi.fd/xxw.log. I noticed there are a lot of warnings: such as "warning #8889: Explicit declaration of the EXTERNAL attribute is required"

**Comment by MichaelLueken-NOAA** [comment]
@XianwuXue-NOAA 

The GSI, EnKF, and utilities have been updated for Cactus and all EXTERNALS have been declared in this issue NOAA-EMC/GSI#192.  The branch in my fork that is associated with this issue is:

https://github.com/MichaelLueken-NOAA/GSI/tree/feature/acorn_debug_cleanup

Now that the GSI and utilities have been tested by Russ Treadon and myself, once the latest PR has been merged to the master, I will be able to push this work.

**Comment by XianwuXue-NOAA** [comment]
@MichaelLueken-NOAA Sounds good. I will discard my changes to use your changes in the future.

**Comment by XianwuXue-NOAA** [comment]
discard these changes
