### ISSUE TITLE
removing the un-necessary grids re-orientation in EnKF IO for FV3-LAM

### ISSUE THREAD

**Issue by TingLei-NOAA** [NOAA-EMC/GSI#361]
In the current EnKF IO for fv3-lam,  in the read and write , the horizontal orientation of the grids would be reversed.
It was implemented like this because, initially, the fv3-lam model was output in the grid layout from NE-SW. The developer chose to this  re-orientation to make sure there will be no  violation of requirement for EnKF (including LETKF and so on).  Though it is clear the serial EnKF which is usually used for regional EnKf doesn't require any specific orientation.  Hence, this extra re-orientation is untouched even when the serial EnKF is run for the later FV3-Lam model of the layout from SW-NE already. 
Of course, it is definitely a waste of the computation resource ,especially for the domains of increasing size. It also gives un-necessary complicacies when dealing with model files on multiple subdomains (https://github.com/NOAA-EMC/GSI/issues/332). 
Thanks to Jeffrey S. Whitaker's confirmation/clarification that all GSI EnKF algorithms don't depend on the orientation of the grids.
Hence, this issue is opened to document the progress of removing this unnecessary re-orientation step.

**Comment by TingLei-daprediction** [comment]
About the verification,  the new codes without the grid-reorientation should give identical results for all variables except for U and V.  That is because, using U as example,  U has (:, ny+1,:) dimensions, namely has an extra line in y direction than other variables. In the current FV3REG EnKF,  as an approximation,  the first ny of U would be taken to be updated alongside other variables and then updating U on ny+1 with updated U on ny.  Hence, whether the grid orientation is done would decide whether the 1:ny or 2:ny+1 (if re-orientation) would be updated and to replace the ny+1 or 1 (if re-orientation).  Hence, it is expected there would be minor differences in the inner domain and bigger differences in lateral boundary y=1 and y=ny+1, that is results show.
