### ISSUE TITLE
Create GSI release branch for v16.3 testing with global-workflow on WCOSS-2

### ISSUE THREAD

**Issue by emilyhcliu** [NOAA-EMC/GSI#391]
Create GSI release branch for v16.3 implementation with global-workflow on WCOSS-2
We are still waiting for the following two items to be merged in GSI  master

(1) [PR #380](https://github.com/NOAA-EMC/GSI/pull/390) to be merged into GSI master
(2) The branch (fix_v16.3) for GSI fix repository.

**Comment by emilyhcliu** [comment]
There is an [update in global workflow](https://github.com/NOAA-EMC/global-workflow/issues/802) that will need to be incorporated into GSI develop before creating the v16.3 release branch.

**Comment by MichaelLueken** [comment]
Issue #392 and PR #393 were created to address the adding of atmos to relevant DMPDIR paths.  Once the atmos subfolder has been added to all GDAs, then PR #393 can be merged to the authoritative develop and the release/gfsda.v16.3.0 release branch can be created from develop.

**Comment by MichaelLueken** [comment]
PR #374 has been merged to the authoritative repository.  The modified fix files in fix_v16.3 have been merged to the authoritative repository's rev2 fix submodule branch.  PR #390 has been submitted to the review committee with a due date of tomorrow and will be merged to the authoritative repository on Friday.

**Comment by emilyhcliu** [comment]
@MichaelLueken-NOAA Thanks for the update.  
Will GSI users be able to create a release branch in the authoritative GSI repository?

**Comment by MichaelLueken** [comment]
@emilyhcliu No, once PR #390 has been merged to the authoritative repository, I will create release/gfsda.v16.3.0 from the authoritative develop branch (unless we want the update from PR #393 as well before creating the release branch, which shouldn't be an issue because it appears as though Kate has largely updated the GDAs to include the atmos subfolder).  Once the release branch has been created, I will grant you (and Andrew and Haixia, if desired) write access to the authoritative repository so that you can make changes to release/gfsda.v16.3.0.

**Comment by emilyhcliu** [comment]
@MichaelLueken-NOAA Got it.  Thanks.  Please create the **release/gfsda.v16.3.0** after  PR #390 is merged tomorrow.  And, yes, please give Andrew, Haixia and I write access to the repository.

**Comment by MichaelLueken** [comment]
@emilyhcliu Today, I will be merging PRs #390, #393, and #395 to the authoritative repository, then create the release/gfsda.v16.3.0 release branch. Once the release branch has been created, I will give you, @ADCollard, and @HaixiaLiu-NOAA write access to the repository so that you can apply changes to release/gfsda.v16.3.0.  I'll let you know once all of these tasks have been completed.

**Comment by emilyhcliu** [comment]
@MichaelLueken-NOAA Thanks!

**Comment by MichaelLueken** [comment]
@emilyhcliu @ADCollard @HaixiaLiu-NOAA All changes have been merged to the authoritative repository and the release/gfsda.v16.3.0 release branch ahs been created.  I have also granted write access to the authoritative repository to the three of you so that you can make additional changes to the release/gfsda.v16.3.0 branch.

If you have any questions, please let me know.

**Comment by emilyhcliu** [comment]
@MichaelLueken-NOAA Thanks you so much!
