### ISSUE TITLE
Develop and test new infrared cloud detection routines

### ISSUE THREAD

**Issue by wx20jjung** [NOAA-EMC/GSI#428]
We plan to test two different techniques to identify clear/cloudy infrared channels within the GSI.  The two targeted are CO2_slicing (Wylie and Menzel) and dual regression (McNally and Watts).

**Comment by wx20jjung** [comment]
A branch was created with initial code changes for the CO2_slicing technique, jung_cloud_tests.

**Comment by RussTreadon-NOAA** [comment]
**WCOSS2 ctests**
Build `wx20jjung:CADS_for_Andrew` at [ac16db4](https://github.com/wx20jjung/GSI/commit/ac16db42837904419f284a24111a924b6cc376cf) on Cactus.   Run ctests with the following results
```
Test project /lfs/h2/emc/da/noscrub/russ.treadon/git/gsi/pr616_fail_ctests.17nov/build
    Start 1: global_4denvar
    Start 2: rtma
    Start 3: rrfs_3denvar_glbens
    Start 4: netcdf_fv3_regional
    Start 5: hafs_4denvar_glbens
    Start 6: hafs_3denvar_hybens
    Start 7: global_enkf
1/7 Test #4: netcdf_fv3_regional ..............***Failed  542.82 sec
2/7 Test #3: rrfs_3denvar_glbens ..............   Passed  605.84 sec
3/7 Test #7: global_enkf ......................   Passed  669.95 sec
4/7 Test #2: rtma .............................   Passed  1102.28 sec
5/7 Test #6: hafs_3denvar_hybens ..............***Failed  1217.38 sec
6/7 Test #5: hafs_4denvar_glbens ..............***Failed  1343.83 sec
7/7 Test #1: global_4denvar ...................***Failed  1442.46 sec

43% tests passed, 4 tests failed out of 7

Total Test time (real) = 1443.22 sec

The following tests FAILED:
          1 - global_4denvar (Failed)
          4 - netcdf_fv3_regional (Failed)
          5 - hafs_4denvar_glbens (Failed)
          6 - hafs_3denvar_hybens (Failed)
Errors while running CTest
```
All four tests failed due to non-reproducible results between the updat and contrl `gsi.x`.

Make the following changes in a working copy of `wx20jjung:CADS_for_Andrew` on Cactus:
- `src/gsi/cads.f90`
  - move source code for subroutine`cads_imager_calc` from `setuprad.f90` to `cads.f90`
  - remove `radmod` from the subroutine argument list and, instead, make `radmod` a local structure within `cads_imager_calc`
- `src/gsi/crtm_interface.f90`
  - remove `if cads` logic around block which computes `chan_level`.  This means all calls to `call_crtm` compute `chan_level`  
  - alternatively, we could move the `chan_level` calculation outside the omp parallel section and into its own loop inside an `if cads` block.
- `src/gsi/qcmod.f90`
   - notice that subroutine `qc_geocsr` does not follow the `cld` & `cloudp` pattern found in other qc routines.  Add `cloudp` and use it to load `cld` as is done in other routines.
   - this change is probably not related to lack of WCOSS2 reproducibility.
-  `src/gsi/setuprad.f90`
   - remove source code for `cads_imager_calc`
   - initialize `imager_*` variables to zero for all observations.  This change may not be necessary.
   - remove `radmod` from the call to `cads_imager_calc`
   - replace the constant integer indices for `imager_*` arrays in the calling list for `cads_imager_calc` with `:`. 

Recompile working copy of `wx20jjung:CADS_for_Andrew` with the above changes and rerun ctests on Cactus.  All tests pass.
```
Test project /lfs/h2/emc/da/noscrub/russ.treadon/git/gsi/pr616_pass_ctests.17nov/build
    Start 1: global_4denvar
    Start 2: rtma
    Start 3: rrfs_3denvar_glbens
    Start 4: netcdf_fv3_regional
    Start 5: hafs_4denvar_glbens
    Start 6: hafs_3denvar_hybens
    Start 7: global_enkf
1/1 Test #4: netcdf_fv3_regional ..............   Passed  483.14 sec
2/7 Test #3: rrfs_3denvar_glbens ..............   Passed  485.42 sec
3/7 Test #7: global_enkf ......................   Passed  609.92 sec
4/7 Test #2: rtma .............................   Passed  969.69 sec
5/7 Test #6: hafs_3denvar_hybens ..............   Passed  1211.04 sec
6/7 Test #1: global_4denvar ...................   Passed  1322.89 sec
7/7 Test #5: hafs_4denvar_glbens ..............   Passed  1331.60 sec

100% tests passed, 0 tests failed out of 7


Total Test time (real) = 1331.62 sec
```

The modified working copy of `wx20jjung:CADS_for_Andrew` has been copied to Hera.   Look in directory `/scratch2/NCEPDEV/stmp1/Russ.Treadon/pr616_pass_ctests.17nov`
```
Hera(hfe11):/scratch2/NCEPDEV/stmp1/Russ.Treadon/pr616_pass_ctests.17nov$ git status
On branch CADS_for_Andrew
Your branch is up to date with 'origin/CADS_for_Andrew'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   src/gsi/cads.f90
        modified:   src/gsi/crtm_interface.f90
        modified:   src/gsi/qcmod.f90
        modified:   src/gsi/setuprad.f90

no changes added to commit (use "git add" and/or "git commit -a")
```

**Comment by wx20jjung** [comment]
My latest CADS test with CrIS also look correct.  Please start the pull request again.

**Comment by RussTreadon-NOAA** [comment]
@wx20jjung , please go to PR #616 and request reviews from @ADCollard, @erinjones2, and @RussTreadon-NOAA.  For Andrew and me, click on the Re-request review circle icon.
