### ISSUE TITLE
Correcting bug encountered in read_airs.f90

### ISSUE THREAD

**Issue by MichaelLueken** [NOAA-EMC/GSI#453]
The debug tests don't assimilate Aqua AMSUA data.  A test was run assimilating Aqua AMSUA in debug and the job failed due to a floating invalid on line 778:
https://github.com/NOAA-EMC/GSI/blob/5f020214e8f6ee29c14d85c66cfea5620c7e99d0/src/gsi/read_airs.f90#L778
Printing out values for tsavg and chsst showed NaNs for chsst.  Further investigation pointed to chsst values for AMSUA.  Looking in the code, chsst is only calculated for AIRS, not AMSUA.  Changing the above if statement with:

`if ((airs).and.(chsst > tsavg)) then`

corrected the failure.

This change will be applied, as well as setting chsst to zero at the top of the subroutine to safeguard from this issue in the future.

**Comment by RussTreadon-NOAA** [comment]
Based on discussions in PR #454 it is has been decided that additional testing is necessary before the changes (or subsequent development) outlined in this issue are merged into develop.   As such, PR #454 has been closed.  A new PR will be opened when testing (and/or development) is complete.

**Comment by RussTreadon-NOAA** [comment]
@ADCollard and @wx20jjung ,  the GSI Handling Review team is going through old GSI issues to see which, if any, may be closed.  

The problem Mike reports in this issue is still present.

When processing aqua_airs variable `chsst` is not initialized prior to its being used in the logical test below [(line 777](https://github.com/NOAA-EMC/GSI/blob/44a8f59ef5cb6def27ba27fcc6a35c074a30332b/src/gsi/read_airs.f90#L777))
```
!       Map obs to grids
        if (chsst > tsavg) then
           call finalcheck(dist1,crit1,itx,iuse)
        else
           call finalcheck(one,crit1,itx,iuse)
        endif
```

`read_airs.f90` only sets `chsst` when processing aqua_airs.

Shall we 
1. leave `read_airs.f90` as is and close this issue, or 
2. keep this issue and set `chsst` to an acceptable value for aqua_amsua?

**Comment by ADCollard** [comment]
@RussTreadon-NOAA As AIRS is no longer assimilated I suggest closing this issue.  We can re-open if there is a need later.

**Comment by wx20jjung** [comment]
Not sure why there are 3 variations of chest.  The logic has other issues
but NCEP doesn't get AIRS any more so testing would be difficult.  My
suggestion is to add the airs logical to the if statement

if ( airs .and. chsst > tsavg) then
