### ISSUE TITLE
a bug in read_obs.F90 missing N21 for EARS and DBnet

### ISSUE THREAD

**Issue by HaixiaLiu-NOAA** [NOAA-EMC/GSI#506]
Jim Jung reported a bug in read_obs.F90 in v16.3 GSI tag: the NOAA21 EARS and DBnet are missing in this routine.

The read_obs has the initial information for n21
      else if(jsatid == 'n21' .or. jsatid == 'j2')then
         kidsat=226

But further down there are loops for EARS and DB net.  N21 is missing in this section.
                   dplat(i) == 'n19' .or. dplat(i) == 'npp' .or. &
                   dplat(i) == 'n20' .or. &
                   dplat(i) == 'metop-a' .or. dplat(i) == 'metop-b' .or. &

**Comment by ADCollard** [comment]
@HaixiaLiu-NOAA We should decide whether we want to add this to the v16.3 release branch or just to develop.   I am working on the assumption that we will not be making code changes in the spring, so that implementation will have to be just with global data.

Thanks to you and @wx20jjung for spotting this.

**Comment by HaixiaLiu-NOAA** [comment]
@ADCollard we would definitely need to fix this in the develop branch. We can decide later if this fix can be added in the spring upgrade.

**Comment by wx20jjung** [comment]
The regional groups should probably be included in the various decisions.
Jim

**Comment by hu5970** [comment]
This issue is solved in PR #630
