### ISSUE TITLE
Adjusted GPS OmF 

### ISSUE THREAD

**Issue by DavidHuber-NOAA** [NOAA-EMC/GSI#573]
The metadata diagnostic file for GPS observations includes an adjusted and unadjusted OmF value.  The calculations for these quantities are identical ([genstats_gps.f90#785-786](https://github.com/NOAA-EMC/GSI/blob/48ea34a9afbcec7b41e44dcd3cdf656bc1d49503/src/gsi/genstats_gps.f90#L785-L786)):
```
           call nc_diag_metadata("Obs_Minus_Forecast_adjusted",           sngl(gps_allptr%rdiag(17))*sngl(gps_allptr%rdiag(5)) )
           call nc_diag_metadata("Obs_Minus_Forecast_unadjusted",         sngl(gps_allptr%rdiag(17))*sngl(gps_allptr%rdiag(5)) )
```
Is this the intention?

**Comment by LidiaCucurull-NOAA** [comment]
I did not write this part of the code. What is the purpose of "adjusted" and "unadjusted" here and how is it used for other observations? I would expect that who coded this had something in mind to be applied to all observations (at the moment or later in the future).

**Comment by RussTreadon-NOAA** [comment]
@XuanliLi-NOAA , @DavidHuber-NOAA found that [lines 785 and 786](https://github.com/NOAA-EMC/GSI/blob/44a8f59ef5cb6def27ba27fcc6a35c074a30332b/src/gsi/genstats_gps.f90#L785-L786) of `src/gsi/genstats_gps.f90` write the same quantity to different variables in the conventional diagnostic file.

```
           call nc_diag_metadata_to_single("Obs_Minus_Forecast_adjusted", gps_allptr%rdiag(17),gps_allptr%rdiag(5),"*")
           call nc_diag_metadata_to_single("Obs_Minus_Forecast_unadjusted",gps_allptr%rdiag(17),gps_allptr%rdiag(5),"*")
```

Do you know if this is intentional (e.g., a placeholder for future development) or an error?

I'm going through old GSI issues and trying to determine which issues we can close and which issues we need to keep open.  Hence my question.

**Comment by XuanliLi-NOAA** [comment]
This has been present for a while, I observed it in v16.1. I'm not aware of the purpose of the "Obs_Minus_Forecast_unadjusted". It might just be an attempt to align with the variables for other conventional data.

**Comment by RussTreadon-NOAA** [comment]
Makes sense.  I'll close this issue.
