### ISSUE TITLE
Address debug build and run issues for HAFS GSI

### ISSUE THREAD

**Issue by BijuThomas-NOAA** [NOAA-EMC/GSI#661]
The HAFS application regression tests failed at the GSI level on the Jet platform and upon debugging, it appears that the variables **toff** and **t4dv** in the subroutine read_radar_l2rw_novadqc(read_radar.f90) were uninitialized and get assigned NaN values. Not totally sure that these are the reasons for HAFS RT failures on 
Jet, but it would be helpful if these variables could be properly initialized.

**Comment by RussTreadon-NOAA** [comment]
@BijuThomas-NOAA , may this issue be closed?

**Comment by BijuThomas-NOAA** [comment]
@RussTreadon-NOAA Would like to see this issue be fixed.

**Comment by RussTreadon-NOAA** [comment]
@BijuThomas-NOAA , it is fine to leave the issue open.  We no longer have a GSI code manager.  All changes originate from developers.  Therefore, please have someone on your team our yourself open a PR to fix the problem identified in this issue.

**Comment by RussTreadon-NOAA** [comment]
This issue will be closed in six weeks (January 23, 2024) if it remains inactive at that time.

**Comment by BijuThomas-NOAA** [comment]
@RussTreadon-NOAA Someone in our HAFS team will look into this issue. Thanks

**Comment by RussTreadon-NOAA** [comment]
Great, thank you @BijuThomas-NOAA , for the update.

**Comment by XuLu-NOAA** [comment]
Hi, @RussTreadon-NOAA and @BijuThomas-NOAA , 
1. The toff is the time offset based on the start of the DA time window. In the current code, toff is not properly assigned and will result in all the ground radar observations to be considered at -3h when using FGAT or 4DEnVar. This is an error and will affect the DA results for those radar obs. The right fix is to use time_offset from obsmod.f90 to correct the time labels for each ob. 
2. The t4dv is a variable used in the read_radar subroutine, not in read_radar_l2rw_novadqc. In the read_radar_l2rw_novadqc subroutine, the right fix is to use t4dv0 instead of t4dv.
3. I also found other uninitialized variables that will fail the GSI in debug mode: zsges in read_radar_l2rw_novadqc (read_radar.f90) should be calculated using the deter_zsfc_model subroutine, and dlnpsob in read_fl_hdob.f90 should be assigned with a value of 1000 since the SFMR observations do not provide any surface pressure sampling.

**Comment by RussTreadon-NOAA** [comment]
Thank you @XuLu-NOAA for looking into this issue, identifying the reason for existing and new problems, and proposing solutions.  To move forward, can someone fork off the current head of GSI `develop`, commit the proposed fixes to the fork, and open a PR to merge the fork into `develop`?
