### ISSUE TITLE
spake stack on Hera and Jet

### ISSUE THREAD

**Issue by hu5970** [NOAA-EMC/GSI#663]
The ufs model is updating to use spack stack 1.5.1. But it points to
Hera:   prepend_path("MODULEPATH", "/scratch1/NCEPDEV/nems/role.epic/spack-stack/spack-stack-1.5.1/envs/unified-env/install/modulefiles/Core")
JET: prepend_path("MODULEPATH", "/mnt/lfs4/HFIP/hfv3gfs/role.epic/spack-stack/spack-stack-1.5.1/envs/unified-env/install/modulefiles/Core")

While the GSI points to:
Hera: prepend_path("MODULEPATH", "/scratch1/NCEPDEV/nems/role.epic/spack-stack/spack-stack-1.5.1/envs/gsi-addon/install/modulefiles/Core")
JET: prepend_path("MODULEPATH", "/mnt/lfs4/HFIP/hfv3gfs/role.epic/spack-stack/spack-stack-1.5.1/envs/gsi-addon/install/modulefiles/Core")

Anyone know what are differences between unified-env and gsi-addon? Or what module is missing in unified-env for GSI to compile and run?

**Comment by RussTreadon-NOAA** [comment]
Not sure this fully answers your question, but here is a g-w comment from Dave about gsi-addon:  
https://github.com/NOAA-EMC/global-workflow/issues/1868#issuecomment-1829886254

**Comment by DavidHuber-NOAA** [comment]
Yeah, the gsi-addon environment is built on top of the unified-env and just adds a few libraries.  It should work with the UFS when it is upgraded to spack-stack/1.5.1/unified-env.

**Comment by hu5970** [comment]
@DavidHuber-NOAA I do not know how those spack-stacks are maintained. The FV3 model is testing to use 1.5.1. If they found some module in unified-env need to be updated. Will gsi-addon get the same module version update automatically. Why those libraries needed by GSI cannot be part of unified-env?

**Comment by DavidHuber-NOAA** [comment]
@hu5970 If a library is installed into unified-env, then the module files in gsi-addon may need to be updated afterwards.  I believe this is a simple step with a single command to generate all of the module files, though it's possible that the installation in gsi-addon would need to be refreshed.

JCSDA manages the spack-stack repository and a combination of JCSDA, EPIC, and EMC staff manages the builds.  The repository, [here](https://github.com/JCSDA/spack-stack), allows users to request installations through issues and also report any problems.

There are a total of 6 libraries installed in gsi-addon that are not in unified-env.  It was built this way because 1) it's easier to maintain, 2) this was initially a test environment, and 3) (I believe) that one pair of those libraries, met/9.1.3 and metplus/3.1.1, would have caused conflicts in unified-env's met/11.1.0 and metplus/5.1.0.  These pair of libraries are actually needed for EMC_verif-global -- the global verification system.  I had requested them as part of the installation to support the upgrade of the entire global-workflow pipeline, in particular the GSI, GFS-utils, and EMC_verif-global.

Of the remaining 4 libraries, two were needed for the GSI: bufr/11.7.0 and gsi-ncdiag/1.1.2.  bufr/11.7.0 is need because of runtime performance issues with bufr/12.0.0 (which is installed in unified-env).  gsi-ncdiag/1.1.2 fixed a memory over-allocation when appending to netCDF files which had existed since its inception, but only materialized when hdf5 was upgraded to 1.14.0.

The final two libraries were needed by the GFS-utils and are the same versions as are available in unified-env, but with added 8-byte integer support: w3emc/2.10.0 and ip/4.3.0.

**Comment by RussTreadon-NOAA** [comment]
@hu5970 , is @DavidHuber-NOAA 's reply sufficient?  If so, please close this issue.  If not, what else do you need to know?

**Comment by RussTreadon-NOAA** [comment]
@hu5970 , may we close this issue?

**Comment by hu5970** [comment]
@RussTreadon-NOAA @DavidHuber-NOAA  Thanks for detailed explanation of the spack-stack gsi-addon. Please close this issue.
