### ISSUE TITLE
Update global_4denvar and global_enkf ctests to reflect GFS v17

### ISSUE THREAD

**Issue by RussTreadon-NOAA** [NOAA-EMC/GSI#759]
The global_4denvar (`gsi.x`) and global_enkf (`enkf.x`) scripts and namelists 
- `regression/global_4denvar.sh`
- `regression/global_enkf.sh`
- `regression/regression_namelists.sh`
- `regression/regression_namelists_db.sh`

should reflect how we intend to run `gsi.x` and `enkf.x` in GFS v17.   This issue is opened to document these changes.

**Comment by RussTreadon-NOAA** [comment]
@CatherineThomas-NOAA , @emilyhcliu :  Any input regarding what needs to change?  Whom else should we tag for input?

**Comment by CatherineThomas-NOAA** [comment]
@RussTreadon-NOAA : One that immediately comes to my mind is that `reducedgrid` needs to be set to .false. for the EnKF.  I'll take a closer look tomorrow and circle back to you for the rest.

**Comment by RussTreadon-NOAA** [comment]
@CatherineThomas-NOAA , if you have log files from a GFS v17 parallel, I can get the namelist changes from these.  No need to add to your workload.

**Comment by RussTreadon-NOAA** [comment]
Work for this issue will be done in [`RussTreadon-NOAA:feature/global_ctests`](https://github.com/RussTreadon-NOAA/GSI/tree/feature/global_ctests)

**Comment by CatherineThomas-NOAA** [comment]
@RussTreadon-NOAA :  Here is what I saw in a quick run through of some logs, ignoring known differences in resolution/iterations

deterministic (regression v g-w develop)
- IMP_PHYSICS = 11 v 8
- TA2TB = F v T
- OPTCONV = 0.05 v 0.0
- CRIS_CADS/IASI_CADS = T v F

ensemble (regression v g-w develop)
- READIN_LOCALIZATION = T v F
- REDUCEDGRID = T v F
- IMP_PHYSICS = 11 v 8

Comments
- imp_physics is the switch to from GFDL (11) to Thompson (8)
- The CADS parameters were set to F for now by Jim J in the workflow until further testing was completed. 
- I know optconv was added for improved minimization, but I'm unsure of the tested/desired value.  
- I believe ta2tb should be true, @emilyhcliu can confirm.
- readin_localization should be set to F due to the model-space localization LETKF
- reducedgrid should be set to F

I did not look at the obs bufrs list.  I have a recent g-w test here if anyone wants to look at the namelists more closely:
`/scratch2/NCEPDEV/stmp1/Catherine.Thomas/ROTDIRS/archive_restartb/`

**Comment by RussTreadon-NOAA** [comment]
Thank you @CatherineThomas-NOAA .  I'll digest your findings, look at some log files, and update global_4denvar and global_enkf namelists accordingly.
